// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authen.proto

package authen

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 空のmessage
type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type RegistrationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{1}
}

func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RegistrationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RegistrationResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationResult) Reset()         { *m = RegistrationResult{} }
func (m *RegistrationResult) String() string { return proto.CompactTextString(m) }
func (*RegistrationResult) ProtoMessage()    {}
func (*RegistrationResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{2}
}

func (m *RegistrationResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResult.Unmarshal(m, b)
}
func (m *RegistrationResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResult.Marshal(b, m, deterministic)
}
func (m *RegistrationResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResult.Merge(m, src)
}
func (m *RegistrationResult) XXX_Size() int {
	return xxx_messageInfo_RegistrationResult.Size(m)
}
func (m *RegistrationResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResult proto.InternalMessageInfo

func (m *RegistrationResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *RegistrationResult) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistrationResult) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RegistrationResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type LoginRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{4}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *LoginResult) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *LoginResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type LogoutRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{5}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResult) Reset()         { *m = LogoutResult{} }
func (m *LogoutResult) String() string { return proto.CompactTextString(m) }
func (*LogoutResult) ProtoMessage()    {}
func (*LogoutResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{6}
}

func (m *LogoutResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResult.Unmarshal(m, b)
}
func (m *LogoutResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResult.Marshal(b, m, deterministic)
}
func (m *LogoutResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResult.Merge(m, src)
}
func (m *LogoutResult) XXX_Size() int {
	return xxx_messageInfo_LogoutResult.Size(m)
}
func (m *LogoutResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResult.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResult proto.InternalMessageInfo

func (m *LogoutResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type MaintenanceRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaintenanceRequest) Reset()         { *m = MaintenanceRequest{} }
func (m *MaintenanceRequest) String() string { return proto.CompactTextString(m) }
func (*MaintenanceRequest) ProtoMessage()    {}
func (*MaintenanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{7}
}

func (m *MaintenanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaintenanceRequest.Unmarshal(m, b)
}
func (m *MaintenanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaintenanceRequest.Marshal(b, m, deterministic)
}
func (m *MaintenanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintenanceRequest.Merge(m, src)
}
func (m *MaintenanceRequest) XXX_Size() int {
	return xxx_messageInfo_MaintenanceRequest.Size(m)
}
func (m *MaintenanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintenanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaintenanceRequest proto.InternalMessageInfo

func (m *MaintenanceRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *MaintenanceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MaintenanceResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaintenanceResult) Reset()         { *m = MaintenanceResult{} }
func (m *MaintenanceResult) String() string { return proto.CompactTextString(m) }
func (*MaintenanceResult) ProtoMessage()    {}
func (*MaintenanceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee8763ef3cea7ebf, []int{8}
}

func (m *MaintenanceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaintenanceResult.Unmarshal(m, b)
}
func (m *MaintenanceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaintenanceResult.Marshal(b, m, deterministic)
}
func (m *MaintenanceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintenanceResult.Merge(m, src)
}
func (m *MaintenanceResult) XXX_Size() int {
	return xxx_messageInfo_MaintenanceResult.Size(m)
}
func (m *MaintenanceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintenanceResult.DiscardUnknown(m)
}

var xxx_messageInfo_MaintenanceResult proto.InternalMessageInfo

func (m *MaintenanceResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Null)(nil), "authen.Null")
	proto.RegisterType((*RegistrationRequest)(nil), "authen.RegistrationRequest")
	proto.RegisterType((*RegistrationResult)(nil), "authen.RegistrationResult")
	proto.RegisterType((*LoginRequest)(nil), "authen.LoginRequest")
	proto.RegisterType((*LoginResult)(nil), "authen.LoginResult")
	proto.RegisterType((*LogoutRequest)(nil), "authen.LogoutRequest")
	proto.RegisterType((*LogoutResult)(nil), "authen.LogoutResult")
	proto.RegisterType((*MaintenanceRequest)(nil), "authen.MaintenanceRequest")
	proto.RegisterType((*MaintenanceResult)(nil), "authen.MaintenanceResult")
}

func init() { proto.RegisterFile("authen.proto", fileDescriptor_ee8763ef3cea7ebf) }

var fileDescriptor_ee8763ef3cea7ebf = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x4f, 0x32, 0x31,
	0x10, 0xfd, 0x76, 0x81, 0x0d, 0xcc, 0xc7, 0xf7, 0x19, 0x07, 0x34, 0xeb, 0xea, 0x81, 0xf4, 0x60,
	0x48, 0x8c, 0x1c, 0xd4, 0xc4, 0xb3, 0x18, 0x0f, 0x10, 0x34, 0x66, 0xbd, 0x98, 0x78, 0xaa, 0xd0,
	0x60, 0x23, 0x69, 0x71, 0xdb, 0xc6, 0x9b, 0x3f, 0xc0, 0x5f, 0x6d, 0x6c, 0x0b, 0xec, 0x22, 0xae,
	0xde, 0xf6, 0xcd, 0x4c, 0x5f, 0xdf, 0x7b, 0x3b, 0x85, 0x26, 0x35, 0xfa, 0x89, 0x89, 0xde, 0x3c,
	0x93, 0x5a, 0x62, 0xe4, 0x10, 0x89, 0xa0, 0x7a, 0x63, 0x66, 0x33, 0x72, 0x09, 0xad, 0x94, 0x4d,
	0xb9, 0xd2, 0x19, 0xd5, 0x5c, 0x8a, 0x94, 0xbd, 0x18, 0xa6, 0x34, 0xee, 0x42, 0x64, 0x14, 0xcb,
	0x06, 0x93, 0x38, 0xe8, 0x04, 0xdd, 0x46, 0xea, 0x11, 0xb6, 0xa1, 0xa6, 0xe5, 0x33, 0x13, 0x71,
	0x68, 0xcb, 0x0e, 0x90, 0x37, 0xc0, 0x22, 0x89, 0x32, 0x33, 0xcb, 0x91, 0xd9, 0x2f, 0xcb, 0x51,
	0x4f, 0x3d, 0xc2, 0x04, 0xea, 0x73, 0xaa, 0xd4, 0xab, 0xcc, 0x26, 0x9e, 0x66, 0x89, 0xf1, 0x00,
	0x1a, 0x8a, 0x29, 0xc5, 0xa5, 0x18, 0x4c, 0xe2, 0x8a, 0x6d, 0xae, 0x0a, 0x9f, 0x8c, 0x4a, 0x53,
	0x6d, 0x54, 0x5c, 0xed, 0x04, 0xdd, 0x5a, 0xea, 0x11, 0xb9, 0x87, 0xe6, 0x48, 0x4e, 0xf9, 0x8f,
	0xea, 0xcb, 0x6e, 0x5e, 0x3a, 0xab, 0xe4, 0x9d, 0x3d, 0xc0, 0x5f, 0xcf, 0x5c, 0x6a, 0xa9, 0x20,
	0x3b, 0xfc, 0x5e, 0x76, 0xa5, 0x20, 0xfb, 0x18, 0xfe, 0x8d, 0xe4, 0x54, 0x1a, 0xbd, 0xd0, 0x5d,
	0xa0, 0x09, 0xd6, 0x68, 0xc8, 0xa1, 0x75, 0x69, 0xc7, 0xcb, 0xc4, 0x90, 0x21, 0xe0, 0x35, 0xe5,
	0x42, 0x33, 0x41, 0xc5, 0x98, 0xfd, 0x8a, 0x3b, 0x97, 0x58, 0x98, 0x4f, 0x8c, 0x1c, 0xc1, 0x76,
	0x81, 0xab, 0xec, 0xe2, 0x93, 0xf7, 0x10, 0xa2, 0x0b, 0xbb, 0x5e, 0x78, 0x05, 0x75, 0xb7, 0x11,
	0x2c, 0xc3, 0xfd, 0x9e, 0xdf, 0xc0, 0x0d, 0x8b, 0x96, 0x24, 0x9b, 0x9b, 0xd6, 0xc8, 0x1f, 0x3c,
	0x83, 0x9a, 0x8d, 0x1f, 0xdb, 0x8b, 0xb1, 0xfc, 0x7f, 0x4e, 0x5a, 0x6b, 0x55, 0x7f, 0xea, 0x1c,
	0x22, 0x17, 0x14, 0xee, 0xe4, 0x06, 0x56, 0x39, 0x27, 0xed, 0xf5, 0xb2, 0x3f, 0x38, 0x84, 0x2d,
	0xeb, 0x96, 0x72, 0x71, 0xe7, 0xa2, 0xc1, 0xa5, 0xbe, 0xaf, 0x91, 0x26, 0x7b, 0x1b, 0x7b, 0x8e,
	0xab, 0x8f, 0xfd, 0xff, 0x2e, 0x0b, 0xcd, 0xc7, 0xd6, 0xd4, 0x6d, 0xf0, 0x18, 0xd9, 0x37, 0x78,
	0xfa, 0x11, 0x00, 0x00, 0xff, 0xff, 0x97, 0xfa, 0x1c, 0x38, 0x93, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenClient is the client API for Authen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenClient interface {
	// 新規ユーザ登録
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResult, error)
	// ログイン認証処理依頼
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResult, error)
	// ログアウト処理依頼
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResult, error)
	//セッション維持リクエスト
	MaintainSession(ctx context.Context, in *MaintenanceRequest, opts ...grpc.CallOption) (*MaintenanceResult, error)
}

type authenClient struct {
	cc *grpc.ClientConn
}

func NewAuthenClient(cc *grpc.ClientConn) AuthenClient {
	return &authenClient{cc}
}

func (c *authenClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResult, error) {
	out := new(RegistrationResult)
	err := c.cc.Invoke(ctx, "/authen.Authen/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResult, error) {
	out := new(LoginResult)
	err := c.cc.Invoke(ctx, "/authen.Authen/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResult, error) {
	out := new(LogoutResult)
	err := c.cc.Invoke(ctx, "/authen.Authen/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenClient) MaintainSession(ctx context.Context, in *MaintenanceRequest, opts ...grpc.CallOption) (*MaintenanceResult, error) {
	out := new(MaintenanceResult)
	err := c.cc.Invoke(ctx, "/authen.Authen/MaintainSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenServer is the server API for Authen service.
type AuthenServer interface {
	// 新規ユーザ登録
	Register(context.Context, *RegistrationRequest) (*RegistrationResult, error)
	// ログイン認証処理依頼
	Login(context.Context, *LoginRequest) (*LoginResult, error)
	// ログアウト処理依頼
	Logout(context.Context, *LogoutRequest) (*LogoutResult, error)
	//セッション維持リクエスト
	MaintainSession(context.Context, *MaintenanceRequest) (*MaintenanceResult, error)
}

// UnimplementedAuthenServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenServer struct {
}

func (*UnimplementedAuthenServer) Register(ctx context.Context, req *RegistrationRequest) (*RegistrationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedAuthenServer) Login(ctx context.Context, req *LoginRequest) (*LoginResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthenServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedAuthenServer) MaintainSession(ctx context.Context, req *MaintenanceRequest) (*MaintenanceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaintainSession not implemented")
}

func RegisterAuthenServer(s *grpc.Server, srv AuthenServer) {
	s.RegisterService(&_Authen_serviceDesc, srv)
}

func _Authen_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authen.Authen/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authen_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authen.Authen/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authen_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authen.Authen/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authen_MaintainSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaintenanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenServer).MaintainSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authen.Authen/MaintainSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenServer).MaintainSession(ctx, req.(*MaintenanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authen_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authen.Authen",
	HandlerType: (*AuthenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Authen_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Authen_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Authen_Logout_Handler,
		},
		{
			MethodName: "MaintainSession",
			Handler:    _Authen_MaintainSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authen.proto",
}
