// Code generated by protoc-gen-go. DO NOT EDIT.
// source: socket.proto

package socket

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 空のmessage
type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type UpdateRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *UpdateRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type StatusResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResult) Reset()         { *m = StatusResult{} }
func (m *StatusResult) String() string { return proto.CompactTextString(m) }
func (*StatusResult) ProtoMessage()    {}
func (*StatusResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{2}
}

func (m *StatusResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResult.Unmarshal(m, b)
}
func (m *StatusResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResult.Marshal(b, m, deterministic)
}
func (m *StatusResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResult.Merge(m, src)
}
func (m *StatusResult) XXX_Size() int {
	return xxx_messageInfo_StatusResult.Size(m)
}
func (m *StatusResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResult proto.InternalMessageInfo

func (m *StatusResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type InfoRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{3}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type InfoResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	QuestionId           int64    `protobuf:"varint,3,opt,name=questionId,proto3" json:"questionId,omitempty"`
	QuestionSeq          int64    `protobuf:"varint,4,opt,name=questionSeq,proto3" json:"questionSeq,omitempty"`
	DeterminationFlag    bool     `protobuf:"varint,5,opt,name=determinationFlag,proto3" json:"determinationFlag,omitempty"`
	TargetNumber         int32    `protobuf:"varint,6,opt,name=targetNumber,proto3" json:"targetNumber,omitempty"`
	Question             string   `protobuf:"bytes,7,opt,name=question,proto3" json:"question,omitempty"`
	Answer1              string   `protobuf:"bytes,8,opt,name=answer1,proto3" json:"answer1,omitempty"`
	Answer2              string   `protobuf:"bytes,9,opt,name=answer2,proto3" json:"answer2,omitempty"`
	Answer1Number        int32    `protobuf:"varint,10,opt,name=answer1number,proto3" json:"answer1number,omitempty"`
	Answer2Number        int32    `protobuf:"varint,11,opt,name=answer2number,proto3" json:"answer2number,omitempty"`
	TimeLimit            string   `protobuf:"bytes,12,opt,name=timeLimit,proto3" json:"timeLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResult) Reset()         { *m = InfoResult{} }
func (m *InfoResult) String() string { return proto.CompactTextString(m) }
func (*InfoResult) ProtoMessage()    {}
func (*InfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{4}
}

func (m *InfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResult.Unmarshal(m, b)
}
func (m *InfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResult.Marshal(b, m, deterministic)
}
func (m *InfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResult.Merge(m, src)
}
func (m *InfoResult) XXX_Size() int {
	return xxx_messageInfo_InfoResult.Size(m)
}
func (m *InfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResult proto.InternalMessageInfo

func (m *InfoResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *InfoResult) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *InfoResult) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *InfoResult) GetQuestionSeq() int64 {
	if m != nil {
		return m.QuestionSeq
	}
	return 0
}

func (m *InfoResult) GetDeterminationFlag() bool {
	if m != nil {
		return m.DeterminationFlag
	}
	return false
}

func (m *InfoResult) GetTargetNumber() int32 {
	if m != nil {
		return m.TargetNumber
	}
	return 0
}

func (m *InfoResult) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *InfoResult) GetAnswer1() string {
	if m != nil {
		return m.Answer1
	}
	return ""
}

func (m *InfoResult) GetAnswer2() string {
	if m != nil {
		return m.Answer2
	}
	return ""
}

func (m *InfoResult) GetAnswer1Number() int32 {
	if m != nil {
		return m.Answer1Number
	}
	return 0
}

func (m *InfoResult) GetAnswer2Number() int32 {
	if m != nil {
		return m.Answer2Number
	}
	return 0
}

func (m *InfoResult) GetTimeLimit() string {
	if m != nil {
		return m.TimeLimit
	}
	return ""
}

type DoneRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	QuestionId           int64    `protobuf:"varint,3,opt,name=questionId,proto3" json:"questionId,omitempty"`
	QuestionSeq          int64    `protobuf:"varint,4,opt,name=questionSeq,proto3" json:"questionSeq,omitempty"`
	DeterminationFlag    bool     `protobuf:"varint,5,opt,name=determinationFlag,proto3" json:"determinationFlag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneRequest) Reset()         { *m = DoneRequest{} }
func (m *DoneRequest) String() string { return proto.CompactTextString(m) }
func (*DoneRequest) ProtoMessage()    {}
func (*DoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{5}
}

func (m *DoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneRequest.Unmarshal(m, b)
}
func (m *DoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneRequest.Marshal(b, m, deterministic)
}
func (m *DoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneRequest.Merge(m, src)
}
func (m *DoneRequest) XXX_Size() int {
	return xxx_messageInfo_DoneRequest.Size(m)
}
func (m *DoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DoneRequest proto.InternalMessageInfo

func (m *DoneRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *DoneRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DoneRequest) GetQuestionId() int64 {
	if m != nil {
		return m.QuestionId
	}
	return 0
}

func (m *DoneRequest) GetQuestionSeq() int64 {
	if m != nil {
		return m.QuestionSeq
	}
	return 0
}

func (m *DoneRequest) GetDeterminationFlag() bool {
	if m != nil {
		return m.DeterminationFlag
	}
	return false
}

type DoneResult struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoneResult) Reset()         { *m = DoneResult{} }
func (m *DoneResult) String() string { return proto.CompactTextString(m) }
func (*DoneResult) ProtoMessage()    {}
func (*DoneResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b39cc5e3943e1cc, []int{6}
}

func (m *DoneResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoneResult.Unmarshal(m, b)
}
func (m *DoneResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoneResult.Marshal(b, m, deterministic)
}
func (m *DoneResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoneResult.Merge(m, src)
}
func (m *DoneResult) XXX_Size() int {
	return xxx_messageInfo_DoneResult.Size(m)
}
func (m *DoneResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DoneResult.DiscardUnknown(m)
}

var xxx_messageInfo_DoneResult proto.InternalMessageInfo

func (m *DoneResult) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*Null)(nil), "socket.Null")
	proto.RegisterType((*UpdateRequest)(nil), "socket.UpdateRequest")
	proto.RegisterType((*StatusResult)(nil), "socket.StatusResult")
	proto.RegisterType((*InfoRequest)(nil), "socket.InfoRequest")
	proto.RegisterType((*InfoResult)(nil), "socket.InfoResult")
	proto.RegisterType((*DoneRequest)(nil), "socket.DoneRequest")
	proto.RegisterType((*DoneResult)(nil), "socket.DoneResult")
}

func init() { proto.RegisterFile("socket.proto", fileDescriptor_6b39cc5e3943e1cc) }

var fileDescriptor_6b39cc5e3943e1cc = []byte{
	// 421 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0xbd, 0x6b, 0x6f, 0x73, 0x9b, 0x49, 0x2e, 0xe2, 0x78, 0x95, 0xa5, 0x88, 0x84, 0xa5, 0x48,
	0x41, 0x29, 0x1a, 0x5f, 0xf4, 0xc1, 0x97, 0xfa, 0x45, 0x41, 0x8a, 0x6c, 0xf1, 0x07, 0xa4, 0xed,
	0x58, 0x82, 0xf9, 0x68, 0xb3, 0x1b, 0xfb, 0x17, 0xfc, 0x3b, 0xbe, 0xfb, 0xe3, 0x24, 0xbb, 0x49,
	0x93, 0x20, 0x94, 0x3e, 0xfa, 0x96, 0x73, 0xe6, 0xec, 0x9e, 0xc9, 0xce, 0x19, 0xf0, 0x55, 0xbe,
	0xf9, 0x41, 0x7a, 0xb6, 0x2f, 0x72, 0x9d, 0xa3, 0x63, 0x91, 0x70, 0xe0, 0x7a, 0x59, 0x26, 0x89,
	0xf8, 0x08, 0xb7, 0xdf, 0xf6, 0xdb, 0x48, 0x93, 0xa4, 0x43, 0x49, 0x4a, 0xe3, 0x13, 0x70, 0x15,
	0x29, 0x15, 0xe7, 0xd9, 0x62, 0xcb, 0x59, 0xc0, 0xa6, 0xae, 0x6c, 0x09, 0x7c, 0x0c, 0x8e, 0xd2,
	0x91, 0x2e, 0x15, 0xbf, 0x17, 0xb0, 0xe9, 0x50, 0xd6, 0x48, 0x3c, 0x03, 0x7f, 0x65, 0xbe, 0x24,
	0xa9, 0x32, 0xd1, 0x95, 0xae, 0x30, 0x5f, 0xe6, 0x8a, 0x91, 0xac, 0x91, 0x78, 0x0e, 0xde, 0x22,
	0xfb, 0x9e, 0x5f, 0x64, 0x26, 0x7e, 0x0d, 0x00, 0xac, 0xfa, 0xdc, 0x9d, 0x78, 0x07, 0xc3, 0xfc,
	0x98, 0x51, 0x61, 0x5a, 0x72, 0xa5, 0x05, 0xf8, 0x14, 0xc0, 0x78, 0xd8, 0xbb, 0x07, 0x01, 0x9b,
	0x0e, 0x64, 0x87, 0xc1, 0x00, 0xbc, 0x06, 0xad, 0xe8, 0xc0, 0xaf, 0x8d, 0xa0, 0x4b, 0xe1, 0x0b,
	0x78, 0xb0, 0x25, 0x4d, 0x45, 0x1a, 0x67, 0x51, 0xc5, 0x7d, 0x4a, 0xa2, 0x1d, 0x1f, 0x1a, 0xeb,
	0x7f, 0x0b, 0x28, 0xc0, 0xd7, 0x51, 0xb1, 0x23, 0xbd, 0x2c, 0xd3, 0x35, 0x15, 0xdc, 0x31, 0xef,
	0xd3, 0xe3, 0x70, 0x0c, 0xa3, 0xc6, 0x80, 0xdf, 0x98, 0x66, 0x4f, 0x18, 0x39, 0xdc, 0x44, 0x99,
	0x3a, 0x52, 0xf1, 0x8a, 0x8f, 0x4c, 0xa9, 0x81, 0x6d, 0x25, 0xe4, 0x6e, 0xb7, 0x12, 0xe2, 0x04,
	0x6e, 0x6b, 0x51, 0x66, 0x4d, 0xc1, 0x98, 0xf6, 0xc9, 0x56, 0x15, 0xd6, 0x2a, 0xaf, 0xab, 0xaa,
	0xc9, 0x6a, 0x14, 0x3a, 0x4e, 0xe9, 0x4b, 0x9c, 0xc6, 0x9a, 0xfb, 0x76, 0x14, 0x27, 0x42, 0xfc,
	0x66, 0xe0, 0x7d, 0xc8, 0xb3, 0x0b, 0x53, 0xf2, 0x5f, 0x4c, 0x44, 0x4c, 0x00, 0x6c, 0xcb, 0xe7,
	0xd2, 0x13, 0xfe, 0x61, 0xe0, 0xac, 0xcc, 0x4e, 0xe0, 0x3b, 0xf0, 0xed, 0x2e, 0xd8, 0x28, 0xe3,
	0xa3, 0x59, 0xbd, 0x3a, 0xbd, 0x0d, 0x19, 0xdf, 0x35, 0x74, 0x37, 0xf1, 0xe2, 0x0a, 0xdf, 0x02,
	0x7c, 0x26, 0xbd, 0xa4, 0x63, 0x95, 0x59, 0x7c, 0xd8, 0xa8, 0x3a, 0x79, 0x1f, 0x63, 0x9f, 0xb4,
	0x07, 0x5f, 0x32, 0x7c, 0x03, 0x9e, 0xa4, 0x0d, 0xc5, 0x3f, 0xa9, 0xea, 0xb8, 0x3d, 0xdb, 0x79,
	0xf2, 0xf6, 0x6c, 0xfb, 0x53, 0xe2, 0x6a, 0x7e, 0x7f, 0xee, 0xd9, 0xee, 0xdf, 0x27, 0x91, 0x52,
	0x5f, 0xd9, 0xda, 0x31, 0x7b, 0xfe, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x76, 0x3f,
	0x97, 0xf7, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SocketClient is the client API for Socket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SocketClient interface {
	// 会員情報を更新
	UpdateStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*StatusResult, error)
	// ユーザに関係する最新情報を取得
	GetNewInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (Socket_GetNewInfoClient, error)
	//新着情報を取得したことをサーバに送信
	ReceiveDone(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResult, error)
}

type socketClient struct {
	cc *grpc.ClientConn
}

func NewSocketClient(cc *grpc.ClientConn) SocketClient {
	return &socketClient{cc}
}

func (c *socketClient) UpdateStatus(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*StatusResult, error) {
	out := new(StatusResult)
	err := c.cc.Invoke(ctx, "/socket.Socket/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketClient) GetNewInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (Socket_GetNewInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Socket_serviceDesc.Streams[0], "/socket.Socket/GetNewInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &socketGetNewInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Socket_GetNewInfoClient interface {
	Recv() (*InfoResult, error)
	grpc.ClientStream
}

type socketGetNewInfoClient struct {
	grpc.ClientStream
}

func (x *socketGetNewInfoClient) Recv() (*InfoResult, error) {
	m := new(InfoResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *socketClient) ReceiveDone(ctx context.Context, in *DoneRequest, opts ...grpc.CallOption) (*DoneResult, error) {
	out := new(DoneResult)
	err := c.cc.Invoke(ctx, "/socket.Socket/ReceiveDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocketServer is the server API for Socket service.
type SocketServer interface {
	// 会員情報を更新
	UpdateStatus(context.Context, *UpdateRequest) (*StatusResult, error)
	// ユーザに関係する最新情報を取得
	GetNewInfo(*InfoRequest, Socket_GetNewInfoServer) error
	//新着情報を取得したことをサーバに送信
	ReceiveDone(context.Context, *DoneRequest) (*DoneResult, error)
}

// UnimplementedSocketServer can be embedded to have forward compatible implementations.
type UnimplementedSocketServer struct {
}

func (*UnimplementedSocketServer) UpdateStatus(ctx context.Context, req *UpdateRequest) (*StatusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (*UnimplementedSocketServer) GetNewInfo(req *InfoRequest, srv Socket_GetNewInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetNewInfo not implemented")
}
func (*UnimplementedSocketServer) ReceiveDone(ctx context.Context, req *DoneRequest) (*DoneResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveDone not implemented")
}

func RegisterSocketServer(s *grpc.Server, srv SocketServer) {
	s.RegisterService(&_Socket_serviceDesc, srv)
}

func _Socket_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).UpdateStatus(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Socket_GetNewInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SocketServer).GetNewInfo(m, &socketGetNewInfoServer{stream})
}

type Socket_GetNewInfoServer interface {
	Send(*InfoResult) error
	grpc.ServerStream
}

type socketGetNewInfoServer struct {
	grpc.ServerStream
}

func (x *socketGetNewInfoServer) Send(m *InfoResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Socket_ReceiveDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServer).ReceiveDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/socket.Socket/ReceiveDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServer).ReceiveDone(ctx, req.(*DoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Socket_serviceDesc = grpc.ServiceDesc{
	ServiceName: "socket.Socket",
	HandlerType: (*SocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStatus",
			Handler:    _Socket_UpdateStatus_Handler,
		},
		{
			MethodName: "ReceiveDone",
			Handler:    _Socket_ReceiveDone_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNewInfo",
			Handler:       _Socket_GetNewInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "socket.proto",
}
